:toc:
:numbered:

[[codeSnippets]]
= Code Snippets (Release Candidate)

IMPORTANT: All the values provided in this Code Snippets are demonstration purposes.

[[eRoamingPushEvseData]]
== eRoamingPushEvseData

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepush/v23/operators/{operatorID}/data-records`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepush/v23/operators/{operatorID}/data-records`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
"ActionType": "fullLoad",
"OperatorEvseData": {
  "EvseDataRecord": [
  {
    "Accessibility": "Restricted access",
    "AccessibilityLocation": "ParkingGarage",
    "AdditionalInfo": [
      {
        "lang": "en",
        "value": "This charging station is for testing purposes"
      }
    ],
    "Address": {
        "City": "Berlin",
        "Country": "DEU",
        "Floor": "6OG",
        "HouseNum": "22",
        "PostalCode": "10829",
        "Region": "Berlin",
        "Street": "EUREF CAMPUS",
        "TimeZone": "UTC+01:00",
        "ParkingFacility": true,
        "ParkingSpot": "E36"
        },
    "AuthenticationModes": [
      "NFC RFID Classic",
      "REMOTE"
        ],
    "CalibrationLawDataAvailability":"Local",
    "ChargingFacilities": [
      {
        "Amperage": 32,
        "Power": 22,
        "PowerType": "AC_3_PHASE",
        "Voltage":480,
        "ChargingModes": [
          "Mode_4"
          ]
       }
      ],
    "ChargingPoolID": "DE*ABC*P1234TEST*1",
    "ChargingStationID": "TEST 1",
    "ChargingStationImage": "http://www.testlink.com",
    "ChargingStationNames": [
      {
        "lang": "en",
        "value": "ABC Charging Station Test"
      },
      {
        "lang": "de",
        "value": "ABC Testladestation"
      }
    ],
    "ChargingStationLocationReference":[
      {
        "lang": "en",
        "value": "Charging station is inside Hubject Officem Parking Lot"
      }
    ],
    "ClearinghouseID": "TEST ID",
    "DynamicInfoAvailable": "true",
    "DynamicPowerLevel": true,
    "EvseID": "DE*XYZ*ETEST1",
    "EnergySource": [
      {
       "Energy":"Solar",
       "Percentage": 85
      },
      {
       "Energy": "Wind",
       "Percentage": 15
      }
     ],
    "EnvironmentalImpact":{
      "CO2Emission": 30.3
     },
    "GeoChargingPointEntrance": {
      "Google": {
        "Coordinates": "52.480495 13.356465"
       }
      },
    "GeoCoordinates": {
      "Google": {
        "Coordinates": "52.480495 13.356465"
        }
      },
    "HardwareManufacturer":"Charger Hardware Muster Company",
    "HotlinePhoneNumber": "+49123123123123",
    "HubOperatorID": "DE*ABC",
    "IsHubjectCompatible": true,
    "IsOpen24Hours": false,
    "MaxCapacity": 50,
    "OpeningTimes": [
      {
        "Period": [
          {
            "begin": "09:00",
            "end": "18:00"
          }
        ],
        "on": "Everyday"
      }
    ],
    "PaymentOptions": [
      "No Payment"
    ],
    "Plugs": [
      "Type 2 Outlet"
    ],
    "RenewableEnergy": true,
    "SubOperatorName":"XYZ Technologies",
    "ValueAddedServices": [
      "Reservation"
    ],
    "deltaType": "insert",
    "lastUpdate": "2018-01-23T14:04:29.377Z"
   }
  ],
  "OperatorID": "DE*ABC",
  "OperatorName": "ABC technologies"
 }
}
----

=== Response Code
[source,JSON]
----
{
    "CPOPartnerSessionID": "string",
    "EMPPartnerSessionID": "string",
    "Result": true,
    "SessionID": "string",
    "StatusCode": {
        "AdditionalInfo": "Success",
        "Code": "000",
        "Description": "string"
    }
}
----

[[eRoamingPushEVSEStatus]]
== eRoamingPushEVSEStatus

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepush/v21/operators/{operatorID}/status-records`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepush/v21/operators/{operatorID}/status-records`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/


=== Request Code
[source,JSON]
----
{
  "ActionType": "fullLoad",
  "OperatorEvseStatus": {
  "EvseStatusRecord": [
    {
      "EvseID": "DE*XYZ*ETEST1",
      "EvseStatus": "Available"
    }
  ],
  "OperatorID": "DE*ABC",
  "OperatorName": "ABC technologies"
  }
}
----

=== Response Code
[source,JSON]
----
{
  "CPOPartnerSessionID": "string",
  "EMPPartnerSessionID": "string",
  "Result": true,
  "SessionID": "string",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

[[eRoamingAuthorizeStart]]
== eRoamingAuthorizeStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/start`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/start`

Please note that in case of EMP role this part of the URL '/api/oicp/charging/v21/operators/{operatorID}/authorize/start' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/


=== Request Code

NOTE: This is an example of an Authorize Request. Only one Identification Method can be used

[source,JSON]
----
 {
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "TestSession",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
      "RFIDMifareFamilyIdentification": {
      "UID": "12345ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:21:23.744Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "OperatorID": "DE*ABC",
  "PartnerProductID": "AC 1",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code

[source,JSON]
----
{
  "AuthorizationStatus": "Authorized",
  "AuthorizationStopIdentifications": [
    {
      "RFIDMifareFamilyIdentification": {
        "UID": "1234ABCD"
      },
      "QRCodeIdentification": {
        "EvcoID": "DE-DCB-C12345678-X",
        "HashedPIN": {
          "Function": "Bcrypt",
          "LegacyHashData": {
            "Function": "MD5",
            "Salt": "string",
            "Value": "string"
          },
          "Value": "string"
        },
        "PIN": "1234"
      },
      "PlugAndChargeIdentification": {
        "EvcoID": "DE-DCB-C12345678-X"
      },
      "RemoteIdentification": {
        "EvcoID": "DE-DCB-C12345678-X"
      },
      "RFIDIdentification": {
        "EvcoID": "DE-DCB-C12345678-X",
        "ExpiryDate": "2021-01-23T14:21:36.954Z",
        "PrintedNumber": "9876655",
        "RFID": "mifareCls",
        "UID": "1234ABCD"
      }
    }
  ],
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "ProviderID": "DE-DCB",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

[[eRoamingAuthorizeStop]]
== eRoamingAuthorizeStop

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/stop`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/stop`

NOTE: Please note that this part of the URL '/api/oicp/charging/v21/operators/{operatorID}/authorize/stop' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

NOTE: This is an example of an Authorize Request. Only one Identification Method can be used

[source,JSON]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "TestSession",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
      "RFIDMifareFamilyIdentification": {
      "UID": "12345ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:21:23.744Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "OperatorID": "DE*ABC",
  "PartnerProductID": "AC 1",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code
[source,JSON]
----
 {
  "AuthorizationStatus": "Authorized",
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "ProviderID": "DE-DCB",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

[[eRoamingAuthorizeRemoteStart]]
== eRoamingAuthorizeRemoteStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start`

NOTE: Please note that in case of CPO role this part of the URL '/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

NOTE: This is an example of an Authorize Request. Only one Identification Method can be used

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "EvseID": "DE*XYZ*ETEST1",
  "Identification": {
    "RFIDMifareFamilyIdentification": {
      "UID": "1234ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:23:54.228Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "PartnerProductID": "AC 1",
  "ProviderID": "DE-DCB",
  "SessionID": "string"
}
----

=== Response Code
[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

[[eRoamingAuthorizeRemoteStop]]
== eRoamingAuthorizeRemoteStop

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop`

NOTE: Please note that in case of CPO role this part of the URL '/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ProviderID": "DE-DCB",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

[[ChargeDetailRecord]]
== eRoamingChargeDetailRecord

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/cdrmgmt/v22/operators/{operatorID}/charge-detail-record`

for *PROD* - environment: `https://service.hubject.com/api/oicp/cdrmgmt/v22/operators/{operatorID}/charge-detail-record`

NOTE: Please note that in case of EMP role this part of the URL '/api/oicp/cdrmgmt/v21/operators/{operatorID}/charge-detail-record' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
  "CalibrationLawVerificationInfo":{
    "CalibrationLawCertificateID": "CD-12BD-2783T",
    "PublicKey": "a9sdh839alskldh/WEDjaskdjis20ij2wdpasodpjlkofi3ed3ed",
    "MeteringSignatureUrl": "http://www.meteringexample1234.com",
    "MeteringSignatureEncodingFormat": "UTF-8",
    "SignedMeteringValuesVerificationInstruction": "please follow instructions provided in the mentioned URL"
  },
  "CPOPartnerSessionID": "1234XYZ",
  "ChargingEnd": "2020-09-23T14:17:53.038Z",
  "ChargingStart": "2020-09-23T14:17:53.038Z",
  "ConsumedEnergy": 10,
  "EMPPartnerSessionID": "9876655",
  "EvseID": "DE*XYZ*ETEST1",
  "HubOperatorID": "DE*ABC",
  "HubProviderID": "DE-DCB",
  "Identification": {
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "QRCodeIdentification": {
      "EvcoID": "string",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:17:53.039Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    },
    "RFIDMifareFamilyIdentification": {
      "UID": "1234ABCD"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    }
  },
  "MeterValueEnd": 10,
  "MeterValueInBetween": {
    "meterValues": [
      10
    ]
  },
  "MeterValueStart": 0,
  "SignedMeteringValues": [
    {
      "SignedMeteringValue": "AAAAAAAAAAAAAAABasdno2e89d2ekasdeBBBBBBBBBBBBBBBBCCCCCCCCC23423BBBBBBBBBBBBBAS",
      "MeteringStatus": "Start"
    },
    {
      "SignedMeteringValue": "AAAAAAAAAAAAAAABBBBdaskjhadksiqwd2309nede9owineBBBBBBBBBBBBBCCCCCCCCC23423BBBBBBBBBBBBBAS",
      "MeteringStatus": "End"
    }
  ],
  "PartnerProductID": "AC 1",
  "SessionEnd": "2020-09-23T14:17:53.039Z",
  "SessionID": "string",
  "SessionStart": "2020-09-23T14:17:53.039Z"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[RemoteReservationStart]]
== eRoamingRemoteReservationStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-start-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-start-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code
NOTE: This is an example of an Authorize Request. Only one Identification Method can be used

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "Duration": 15,
  "EMPPartnerSessionID": "2345ABC",
  "EvseID": "DE*XYZ*ETEST1",
  "Identification": {
    "RFIDMifareFamilyIdentification": {
      "UID": "1234ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:23:54.228Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "PartnerProductID": "Reservation",
  "ProviderID": "DE-DCB",
  "SessionID": "string"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[RemoteReservationStop]]
== eRoamingRemoteReservationStop

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-stop-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-stop-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ProviderID": "DE-DCB",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code
[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[PushEVSEPricing]]
== eRoamingPushEVSEPricing

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/dynamicpricing/v10/operators/{operatorID}/evse-pricing`

for *PROD* - environment: `https://service.hubject.com/api/oicp/dynamicpricing/v10/operators/{operatorID}/evse-pricing`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
  "ActionType": "fullLoad",
  "EVSEPricing": [
    {
      "EvseID": "DE*XYZ*ETEST1",
      "EvseIDProductList": [
        "AC 1"
      ],
      "ProviderID": "*"
    }
  ]
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "string",
  "EMPPartnerSessionID": "string",
  "Result": true,
  "SessionID": "string",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[PushPricingProductData]]
== eRoamingPushPricingProductData

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/dynamicpricing/v10/operators/{operatorID}/pricing-products`

for *PROD* - environment: `https://service.hubject.com/api/oicp/dynamicpricing/v10/operators/{operatorID}/pricing-products`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "ActionType": "fullLoad",
    "PricingProductData": {
    "OperatorID": "DE*ABC",
    "OperatorName": "ABC technologies",
    "PricingDefaultPrice": 0,
    "PricingDefaultPriceCurrency": "EUR",
    "PricingDefaultReferenceUnit": "HOUR",
    "PricingProductDataRecords": [
        {
        "AdditionalReferences": [
	  {
            "AdditionalReference": "PARKING FEE",
            "AdditionalReferenceUnit": "HOUR",
            "PricePerAdditionalReferenceUnit": 2
          }
	],
        "IsValid24hours": false,
        "MaximumProductChargingPower": 22,
        "PricePerReferenceUnit": 1,
        "ProductAvailabilityTimes": [
          {
            "Periods": [
              {
                "begin": "09:00",
                "end": "18:00"
              }
            ],
            "on": "Everyday"
          }
        ],
        "ProductID": "AC 1",
        "ProductPriceCurrency": "EUR",
        "ReferenceUnit": "HOUR"
        }
    ],
  "ProviderID": "*"
  }
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "string",
  "EMPPartnerSessionID": "string",
  "Result": true,
  "SessionID": "string",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[eRoamingChargingNotificationStart]]
== eRoamingChargingNotificationStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
	"CPOPartnerSessionID": "1234XYZ",
	"ChargingStart": "2020-09-23T14:17:53.038Z",
	"EMPPartnerSessionID": "2345ABC",
	"EvseID": "DE*XYZ*ETEST1",
	"Identification": {
		"RFIDMifareFamilyIdentification": {
			"UID": "1234ABCD"
		}
	},
	"MeterValueStart": 0,
	"PartnerProductID": "AC 1",
	"SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
	"SessionStart": "2020-09-23T14:17:53.038Z",
	"OperatorID": "DE*ABC",
	"Type": "Start"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[eRoamingChargingNotificationProgress]]
== eRoamingChargingNotificationProgress

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "ChargingStart": "2020-09-23T14:17:53.038Z",
    "EventOccurred": "2020-09-23T14:25:53.038Z",
    "ChargingDuration": 48000,
    "ConsumedEnergyProgress": 9,
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "MeterValueStart": 0,
    "MeterValueInBetween": {
        "meterValues": [
            9
        ]
    },
    "PartnerProductID": "AC 1",
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "SessionStart": "2020-09-23T14:17:53.038Z",
    "Type": "Progress"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[eRoamingChargingNotificationEnd]]
== eRoamingChargingNotificationEnd

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "ChargingEnd": "2020-09-23T14:17:53.038Z",
    "ChargingStart": "2020-09-23T14:50:53.038Z",
    "ConsumedEnergy": 10,
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "MeterValueStart": 0,
    "MeterValueEnd": 10,
    "MeterValueInBetween": {
        "meterValues": [
            0
        ]
    },
    "PartnerProductID": "AC 1",
    "PenaltyTimeStart": "2020-09-23T14:17:53.038Z",
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "SessionStart": "2020-09-23T14:17:53.038Z",
	"SessionEnd": "2020-09-23T14:50:53.038Z",
    "Type": "End"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

[[eRoamingChargingNotificationError]]
== eRoamingChargingNotificationError

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ErrorType": "Connector Error",
    "ErrorAdditionalInfo": "Plug was not connected, EVSEID timed out reached",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "Type": "Error"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

