:toc:
:numbered:

= Code Snippets

== eRoamingPullEVSEData

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepull/v23/providers/{providerID}/data-records`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepull/v23/providers/{providerID}/data-records`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/company/download

=== Request Code
[source,JSON]
----
{
  "AuthenticationModes": [
  "PnC"
  ],
  "Accessibility": [
  "Free publicly accessible"
  ],
  "CalibrationLawDataAvailability": [
  "Local"
  ],
  "CountryCodes": [
    "DEU"
  ],
  "GeoCoordinatesResponseFormat": "Google",
  "IsHubjectCompatible": true,
  "IsOpen24Hours": true,
  "LastCall": "2020-09-23T14:27:43.052Z",
  "OperatorIds": [
    "DE*ABC"
  ],
  "ProviderID": "DE-DCB",
  "RenewableEnergy": true,
  "SearchCenter": {
    "GeoCoordinates": {
      "Google": {
        "Coordinates": "string"
      },
      "DecimalDegree": {
        "Latitude": "string",
        "Longitude": "string"
      },
      "DegreeMinuteSeconds": {
        "Latitude": "string",
        "Longitude": "string"
      }
    },
    "Radius": 0
  }
}
----

=== Response Code

[source,JSON]
----
{
  "content": [
              {
                "Accessibility": "Restricted access",
                "AccessibilityLocation": "ParkingGarage",
                "AdditionalInfo": [
                  {
                    "lang": "en",
                    "value": "This charging station is for testing purposes"
                  }
                ],
                "Address": {
                    "City": "Berlin",
                    "Country": "DEU",
                    "Floor": "6OG",
                    "HouseNum": "22",
                    "PostalCode": "10829",
                    "Region": "Berlin",
                    "Street": "EUREF CAMPUS",
                    "TimeZone": "UTC+01:00",
                    "ParkingFacility": true,
                    "ParkingSpot": "E36"
                    },
                "AuthenticationModes": [
                  "NFC RFID Classic",
                  "REMOTE"
                    ],
                "CalibrationLawDataAvailability":"Local",
                "ChargingFacilities": [
                  {
                    "Amperage": 32,
                    "Power": 22,
                    "PowerType": "AC_3_PHASE",
                    "Voltage":480,
                    "ChargingModes": [
                      "Mode_4"
                      ]
                   }
                  ],
                "ChargingPoolID": "DE*ABC*P1234TEST*1",
                "ChargingStationID": "TEST 1",
                "ChargingStationImage": "http://www.testlink.com",
                "ChargingStationNames": [
                  {
                    "lang": "en",
                    "value": "ABC Charging Station Test"
                  },
                  {
                    "lang": "de",
                    "value": "ABC Testladestation"
                  }
                ],
                "ChargingStationLocationReference":[
                  {
                    "lang": "en",
                    "value": "Charging station is inside Hubject Office Parking Lot"
                  }
                ],
                "ClearinghouseID": "TEST ID",
                "DynamicInfoAvailable": "true",
                "DynamicPowerLevel": true,
                "EvseID": "DE*XYZ*ETEST1",
                "EnergySource": [
                  {
                   "Energy":"Solar",
                   "Percentage": 85
                  },
                  {
                   "Energy": "Wind",
                   "Percentage": 15
                  }
                 ],
                "EnvironmentalImpact":{
                  "CO2Emission": 30.3
                 },
                "GeoChargingPointEntrance": {
                  "Google": {
                    "Coordinates": "52.480495 13.356465"
                   }
                  },
                "GeoCoordinates": {
                  "Google": {
                    "Coordinates": "52.480495 13.356465"
                    }
                  },
                "HardwareManufacturer":"Charger Hardware Muster Company",
                "HotlinePhoneNumber": "+49123123123123",
                "HubOperatorID": "DE*ABC",
                "IsHubjectCompatible": true,
                "IsOpen24Hours": false,
                "MaxCapacity": 50,
                "OpeningTimes": [
                  {
                    "Period": [
                      {
                        "begin": "09:00",
                        "end": "18:00"
                      }
                    ],
                    "on": "Everyday"
                  }
                ],
                "PaymentOptions": [
                  "No Payment"
                ],
                "Plugs": [
                  "Type 2 Outlet"
                ],
                "RenewableEnergy": true,
                "SubOperatorName":"XYZ Technologies",
                "ValueAddedServices": [
                  "Reservation"
                ],
                "deltaType": "insert",
                "lastUpdate": "2018-01-23T14:04:29.377Z",
                "OperatorId": "DE*ABC",
                "OperatorName": "ABC technologies"
           }
      ],
  "number": 0,
  "size": 1,
  "totalElements": 8,
  "last": false,
  "totalPages": 8,
  "first": true,
  "numberOfElements": 1,
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

== eRoamingPullEVSEStatus

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records`

The service description can be found in the OICP protocol version 2.2.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
  "EvseStatus": "Available",
  "ProviderID": "DE-DCB",
  "SearchCenter": {
      "GeoCoordinates": {
        "Google": {
          "Coordinates": "string"
           },
        "DecimalDegree": {
          "Latitude": "string",
          "Longitude": "string"
           },
        "DegreeMinuteSeconds": {
          "Latitude": "string",
          "Longitude": "string"
           }
        },
      "Radius": 0
  }
}
----

=== Response Code
[source,JSON]
----
{
  "EvseStatuses": {
    "OperatorEvseStatus": [
      {
        "EvseStatusRecord": [
          {
            "EvseID": "DE*XYZ*ETEST1",
            "EvseStatus": "Available"
          }
        ],
        "OperatorID": "DE*ABC",
        "OperatorName": "ABC technologies"
      }
    ]
  },
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----
== [[eRoamingAuthorizeStart]]eRoamingAuthorizeStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/start`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/start`

NOTE: Please note that in case of EMP role this part of the URL '/api/oicp/charging/v21/operators/{operatorID}/authorize/start' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code
[source,JSON]
----
 {
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "TestSession",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
      "RFIDMifareFamilyIdentification": {
      "UID": "12345ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:21:23.744Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "OperatorID": "DE*ABC",
  "PartnerProductID": "AC 1",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code
[source,JSON]
----
{
  "AuthorizationStatus": "Authorized",
  "AuthorizationStopIdentifications": [
   {
    "RFIDMifareFamilyIdentification": {
      "UID": "12345ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
      },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:21:23.744Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
     }
    }
  ],
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "ProviderID": "DE-DCB",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "StatusCode": {
      "AdditionalInfo": "Success",
      "Code": "000",
      "Description": "string"
    }
}
----
== eRoamingAuthorizeStop

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/stop`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/operators/{operatorID}/authorize/stop`

NOTE: Please note that this part of the URL '/api/oicp/charging/v21/operators/{operatorID}/authorize/stop' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
 {
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "TestSession",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
      "RFIDMifareFamilyIdentification": {
      "UID": "12345ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:21:23.744Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "OperatorID": "DE*ABC",
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code

[source,JSON]
----
{
  "AuthorizationStatus": "Authorized",
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== eRoamingAuthorizeRemoteStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start`

NOTE: Please note that in case of CPO role this part of the URL '/api/oicp/charging/v21/providers/{providerID}/authorize-remote/start' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "EvseID": "DE*XYZ*ETEST1",
  "Identification": {
    "RFIDMifareFamilyIdentification": {
      "UID": "1234ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:23:54.228Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "PartnerProductID": "AC 1",
  "ProviderID": "DE-DCB",
  "SessionID": "string"
}
----

=== Response Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== eRoamingAuthorizeRemoteStop
The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop`

for *PROD* - environment: `https://service.hubject.com/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop`

NOTE: Please note that in case of CPO role this part of the URL '/api/oicp/charging/v21/providers/{externalId}/authorize-remote/stop' will be added to your URL endpoint when sending the request through our HBS platform.

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ProviderID": "DE-DCB",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----


== eRoamingGetChargeDetailRecord

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/cdrmgmt/v22/providers/{providerID}/get-charge-detail-records-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/cdrmgmt/v22/providers/{providerID}/get-charge-detail-records-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
  "CDRForwarded": false,
  "From": "2020-08-23T14:20:10.285Z",
  "OperatorID": ["DE*ABC"],
  "ProviderID": "DE-DCN",
  "To": "2020-09-23T14:20:10.285Z",
  "SessionID":[
    "string"
  ]
}
----

=== Response Code

[source,JSON]
----
{
  "content": [
                {
                  "CalibrationLawVerificationInfo":{
                    "CalibrationLawCertificateID": "CD-12BD-2783T",
                    "PublicKey": "a9sdh839alskldh/WEDjaskdjis20ij2wdpasodpjlkofi3ed3ed",
                    "MeteringSignatureUrl": "http://www.meteringexample1234.com",
                    "MeteringSignatureEncodingFormat": "UTF-8",
                    "SignedMeteringValuesVerificationInstruction": "please follow instructions provided in the mentioned URL"
                  },
                  "CPOPartnerSessionID": "1234XYZ",
                  "ChargingEnd": "2020-09-23T14:17:53.038Z",
                  "ChargingStart": "2020-09-23T14:17:53.038Z",
                  "ConsumedEnergy": 10,
                  "EMPPartnerSessionID": "9876655",
                  "EvseID": "DE*XYZ*ETEST1",
                  "HubOperatorID": "DE*ABC",
                  "HubProviderID": "DE-DCB",
                  "Identification": {
                    "PlugAndChargeIdentification": {
                      "EvcoID": "DE-DCB-C12345678-X"
                    },
                    "QRCodeIdentification": {
                      "EvcoID": "DE-DCB-C12345678-X",
                      "HashedPIN": {
                        "Function": "Bcrypt",
                        "LegacyHashData": {
                          "Function": "MD5",
                          "Salt": "string",
                          "Value": "string"
                        },
                        "Value": "string"
                      },
                      "PIN": "1234"
                    },
                    "RFIDIdentification": {
                      "EvcoID": "DE-DCB-C12345678-X",
                      "ExpiryDate": "2021-01-23T14:17:53.039Z",
                      "PrintedNumber": "9876655",
                      "RFID": "mifareCls",
                      "UID": "1234ABCD"
                    },
                    "RFIDMifareFamilyIdentification": {
                      "UID": "1234ABCD"
                    },
                    "RemoteIdentification": {
                      "EvcoID": "DE-DCB-C12345678-X"
                    }
                  },
                  "MeterValueEnd": 10,
                  "MeterValueInBetween": {
                    "meterValues": [
                      10
                    ]
                  },
                  "MeterValueStart": 0,
                  "SignedMeteringValues": [
                    {
                      "SignedMeteringValue": "AAAAAAAAAAAAAAABasdno2e89d2ekasdeBBBBBBBBBBBBBBBBCCCCCCCCC23423BBBBBBBBBBBBBAS",
                      "MeteringStatus": "Start"
                    },
                    {
                      "SignedMeteringValue": "AAAAAAAAAAAAAAABBBBdaskjhadksiqwd2309nede9owineBBBBBBBBBBBBBCCCCCCCCC23423BBBBBBBBBBBBBAS",
                      "MeteringStatus": "End"
                    }
                  ],
                  "PartnerProductID": "AC 1",
                  "SessionEnd": "2020-09-23T14:17:53.039Z",
                  "SessionID": "string",
                  "SessionStart": "2020-09-23T14:17:53.039Z"
                }
  ],
  "number": 0,
  "size": 20,
  "totalElements": 2,
  "last": true,
  "totalPages": 1,
  "first": true,
  "numberOfElements": 2,
  "StatusCode": null
}
----


== eRoamingRemoteReservationStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-start-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-start-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "Duration": 15,
  "EMPPartnerSessionID": "2345ABC",
  "EvseID": "DE*XYZ*ETEST1",
  "Identification": {
    "RFIDMifareFamilyIdentification": {
      "UID": "1234ABCD"
    },
    "QRCodeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "HashedPIN": {
        "Function": "Bcrypt",
        "LegacyHashData": {
          "Function": "MD5",
          "Salt": "string",
          "Value": "string"
        },
        "Value": "string"
      },
      "PIN": "1234"
    },
    "PlugAndChargeIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RemoteIdentification": {
      "EvcoID": "DE-DCB-C12345678-X"
    },
    "RFIDIdentification": {
      "EvcoID": "DE-DCB-C12345678-X",
      "ExpiryDate": "2021-01-23T14:23:54.228Z",
      "PrintedNumber": "9876655",
      "RFID": "mifareCls",
      "UID": "1234ABCD"
    }
  },
  "PartnerProductID": "Reservation",
  "ProviderID": "DE-DCB",
  "SessionID": "string"
}
----

=== Response Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----


== eRoamingRemoteReservationStop

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-stop-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/reservation/v11/providers/{providerID}/reservation-stop-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ProviderID": "DE-DCB",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527"
}
----

=== Response Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== eRoamingPullEVSEStatusByID

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records-by-id`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records-by-id`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
"EvseID": [
"DE*XYZ*ETEST1"
],
"ProviderID": "DE-DCB"
}
----

=== Response Code

[source,JSON]
----
{
  "EVSEStatusRecords": {
    "EvseStatusRecord": [
      {
        "EvseID": "DE*XYZ*ETEST1",
        "EvseStatus": "Available"
      }
    ]
  },
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

== eRoamingPullEVSEStatusByOperatorID

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records-by-operator-id`

for *PROD* - environment: `https://service.hubject.com/api/oicp/evsepull/v21/providers/{providerID}/status-records-by-operator-id`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code
[source,JSON]
----
{
"OperatorID": [
"DE*ABC"
],
"ProviderID": "DE-DCB"
}
----

=== Response Code

[source,JSON]
----
{
  "EvseStatuses": {
  "OperatorEvseStatus": [
    {
      "EvseStatusRecord": [
      {
        "EvseID": "DE*XYZ*ETEST1",
        "EvseStatus": "Available"
      }
      ],
      "OperatorID": "DE*ABC",
      "OperatorName": "ABC technologies"
    }
    ]
  },
  "StatusCode": {
  "AdditionalInfo": "Success",
  "Code": "000",
  "Description": "string"
  }
}
----

== eRoamingPushAuthenticationData

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/authdata/v21/providers/{providerID}/push-request`

for *PROD* - environment: `https://service.hubject.com/api/oicp/authdata/v21/providers/{providerID}/push-request`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code
[source,JSON]
----
{
  "ActionType": "fullLoad",
  "ProviderAuthenticationData": {
  "AuthenticationDataRecord": [
    {
      "Identification": {
        "RFIDMifareFamilyIdentification": {
        "UID": "12345ABCD"
        },
        "QRCodeIdentification": {
          "EvcoID": "DE-DCB-C12345678-X",
          "HashedPIN": {
            "Function": "Bcrypt",
            "LegacyHashData": {
              "Function": "MD5",
              "Salt": "string",
              "Value": "string"
            },
            "Value": "string"
          },
          "PIN": "1234"
        },
        "PlugAndChargeIdentification": {
          "EvcoID": "DE-DCB-C12345678-X"
        },
        "RemoteIdentification": {
          "EvcoID": "DE-DCB-C12345678-X"
        },
        "RFIDIdentification": {
          "EvcoID": "DE-DCB-C12345678-X",
          "ExpiryDate": "2021-01-23T14:21:23.744Z",
          "PrintedNumber": "9876655",
          "RFID": "mifareCls",
          "UID": "1234ABCD"
        }
      }
    }
  ],
  "ProviderID": "DE-DCB"
  }
}
----

=== Response Code

[source,JSON]
----
{
  "CPOPartnerSessionID": "string",
  "EMPPartnerSessionID": "string",
  "Result": true,
  "SessionID": "string",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

== eRoamingPullEVSEPricing

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/dynamicpricing/v10/providers/{providerID}/evse-pricing`

for *PROD* - environment: `https://service.hubject.com/api/oicp/dynamicpricing/v10/providers/{providerID}/evse-pricing`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,JSON]
----
{
"LastCall": "2020-09-23T14:33:03.126Z",
"OperatorIDs": [
"DE*ABC"
],
"ProviderID": "DE-DCB"
}
----

=== Response Code

[source,JSON]
----
{
  "EVSEPricing": [
    {
      "EVSEPricing": [
        {
          "EvseID": "DE*XYZ*ETEST1",
          "EvseIDProductList": [
            "AC 1"
          ],
          "ProviderID": "DE-DCB"
        }
      ],
      "OperatorID": "DE*ABC",
      "OperatorName": "ABC technologies"
    }
  ],
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
  }
}
----

== eRoamingPullPricingProductData

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/dynamicpricing/v10/providers/{providerID}/pricing-products`

for *PROD* - environment: `https://service.hubject.com/api/oicp/dynamicpricing/v10/providers/{providerID}/pricing-products`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

===  Request Code

[source,JSON]
----
{
  "LastCall": "2020-09-23T14:33:42.246Z",
  "OperatorIDs": [
    "DE*ABC"
  ]
}
----

=== Response Code

[source,JSON]
----
{
    "CPOPartnerSessionID": "string",
    "EMPPartnerSessionID": "string",
    "Result": true,
    "SessionID": "string",
    "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "string"
    }
}
----
== [[eRoamingChargingNotificationStart]]eRoamingChargingNotificationStart

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
	"CPOPartnerSessionID": "1234XYZ",
	"ChargingStart": "2020-09-23T14:17:53.038Z",
	"EMPPartnerSessionID": "2345ABC",
	"EvseID": "DE*XYZ*ETEST1",
	"Identification": {
		"RFIDMifareFamilyIdentification": {
			"UID": "1234ABCD"
		}
	},
	"MeterValueStart": 0,
	"PartnerProductID": "AC 1",
	"SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
	"SessionStart": "2020-09-23T14:17:53.038Z",
	"OperatorID": "DE*ABC",
	"Type": "Start"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== [[eRoamingChargingNotificationProgress]]eRoamingChargingNotificationProgress

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "ChargingStart": "2020-09-23T14:17:53.038Z",
    "EventOccurred": "2020-09-23T14:25:53.038Z",
    "ChargingDuration": 48000,
    "ConsumedEnergyProgress": 9,
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "MeterValueStart": 0,
    "MeterValueInBetween": {
        "meterValues": [
            9
        ]
    },
    "PartnerProductID": "AC 1",
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "SessionStart": "2020-09-23T14:17:53.038Z",
    "Type": "Progress"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== [[eRoamingChargingNotificationEnd]]eRoamingChargingNotificationEnd

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "ChargingEnd": "2020-09-23T14:50:53.038Z",
    "ChargingStart": "2020-09-23T14:17:53.038Z",
    "ConsumedEnergy": 10,
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "MeterValueStart": 0,
    "MeterValueEnd": 10,
    "MeterValueInBetween": {
        "meterValues": [
            0
        ]
    },
    "PartnerProductID": "AC 1",
    "PenaltyTimeStart": "2020-09-23T14:17:53.038Z",
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "SessionStart": "2020-09-23T14:17:53.038Z",
	"SessionEnd": "2020-09-23T14:50:53.038Z",
    "Type": "End"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

== [[eRoamingChargingNotificationError]]eRoamingChargingNotificationError

The Service End Points to which the below POST command should be sent are:

for *QA* - environment: `https://service-qa.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

for *PROD* - environment: `https://service.hubject.com/api/oicp/notificationmgmt/v11/charging-notifications`

The service description can be found in the OICP protocol version 2.3.
To download the latest OICP Version, please visit our website:
https://www.hubject.com/downloads/

=== Request Code

[source,json]
----
{
    "CPOPartnerSessionID": "1234XYZ",
    "EMPPartnerSessionID": "2345ABC",
    "EvseID": "DE*XYZ*ETEST1",
    "ErrorType": "Connector Error",
    "ErrorAdditionalInfo": "Plug was not connected, EVSEID timed out reached",
    "Identification": {
        "RFIDMifareFamilyIdentification": {
            "UID": "1234ABCD"
        }
    },
    "OperatorID": "DE*ABC",
    "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
    "Type": "Error"
}
----

=== Response Code

[source,json]
----
{
  "CPOPartnerSessionID": "1234XYZ",
  "EMPPartnerSessionID": "2345ABC",
  "Result": true,
  "SessionID": "f98efba4-02d8-4fa0-b810-9a9d50d2c527",
  "StatusCode": {
    "AdditionalInfo": "Success",
    "Code": "000",
    "Description": "Success"
  }
}
----

